name: Build PDF
on:
  push:
    branches:
      - master
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: fadlecturenotes

      - name: Initialize Conda
        run: |
          echo "Initializing Conda"
          conda init bash
          source ~/.bashrc  # Activate the changes made by conda init

      - name: Build Jupyter Book to HTML
        run: |
          conda run -n fadlecturenotes jb build lecturenotes/ --builder html

      - name: List HTML Output Directory
        run: |
          ls -l lecturenotes/_build/html/lectures/  # List files to verify that index.html exists

      - name: Convert HTML to PDF using Base URL
        run: |
          wkhtmltopdf --base-url ${GITHUB_WORKSPACE}/lecturenotes/_build/html/ ${GITHUB_WORKSPACE}/lecturenotes/_build/html/lectures/index.html ${GITHUB_WORKSPACE}/lecturenotes/_build/pdf/book.pdf --debug-javascript

      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: lecturenotes/_build/pdf/book.pdf

      - uses: ncipollo/release-action@v1
        with:
          artifacts: lecturenotes/_build/pdf/book.pdf
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
