name: Build PDF
on:
  push:
    branches:
      - master
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3  # Updated to v3
        with:
          persist-credentials: false
      - name: Install Fonts
        run: |
          sudo apt-get install -y fonts-liberation
          sudo apt-get install -y fonts-cmu
      - name: Install & Update TexLive
        shell: bash -l {0}
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y     \
            texlive-latex-recommended \
            texlive-latex-extra       \
            texlive-fonts-recommended \
            texlive-fonts-extra       \
            texlive-xetex             \
            latexmk                   \
            xindy
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3  # Updated to v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: fadlecturenotes
      - name: Build QuantEcon Mini Example
        shell: bash -l {0}
        run: |
          jb build lecturenotes/ --builder pdflatex
      - uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: pdf
          path: lecturenotes/_build/latex/book.pdf
      - uses: ncipollo/release-action@v1  # Keep this as is, check if a newer version exists
        with:
          artifacts: lecturenotes/_build/latex/book.pdf
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
