name: Build PDF
on:
  push:
    branches:
      - master
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            fonts-liberation \
            fonts-cmu \
            wkhtmltopdf  # Install wkhtmltopdf for HTML to PDF conversion

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: 3.8
          environment-file: environment.yml
          activate-environment: fadlecturenotes

      - name: Build Jupyter Book to HTML
        run: |
          conda activate fadlecturenotes  # Activate the environment
          jb build lecturenotes/ --builder html

      - name: Convert HTML to PDF
        run: |
          wkhtmltopdf lecturenotes/_build/html/index.html lecturenotes/_build/pdf/book.pdf

      - uses: actions/upload-artifact@v3
        with:
          name: pdf
          path: lecturenotes/_build/pdf/book.pdf

      - uses: ncipollo/release-action@v1
        with:
          artifacts: lecturenotes/_build/pdf/book.pdf
          allowUpdates: true
          replacesArtifacts: true
          tag: "latest"
